import com.mmodding.gradle.api.EnvironmentTarget

plugins {
	id 'maven-publish'
	alias libs.plugins.fabric.loom
	alias libs.plugins.mmodding.gradle
}

version = "${project.version}+${libs.versions.minecraft.get()}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	repositories {
		maven {
			name = "JitPack"
			url = "https://jitpack.io"
		}
		maven {
			name = "QuiltMC"
			url = "https://maven.quiltmc.org/repository/release"
		}
		maven {
			name = "Nucleoid"
			url = "https://maven.nucleoid.xyz/releases"
		}
	}
}

dependencies {
	minecraft libs.minecraft
	implementation libs.fabric.loader

	implementation libs.fabric.api
	implementation libs.mmodding

	// Optional Dependencies
	implementation libs.trinkets
}


fabricApi {
	configureDataGeneration() {
		client = true
	}
}

loom {
	mods {
		"archeon" {
			sourceSet("main")
		}
	}
}

mmodding {
	configureFabricModJson {
		name = "Archeon"
		namespace = "archeon"
		group = "com.mmodding"
		description = "This is the Official Version of Archeon. Archeon is a brand new dimension, full of new blocks, mobs and more! All you need to get there is a portal made of Mysterious Stone, filled with a magical energy made by the Wand of Nature!"
		icon = "assets/archeon/icon.png"
		addAuthor("MModding Team")
		addContributor("Aethyus (Author, Art Director, Project Manager)")
		addContributor("Aeramisu (Art Director, Project Manager, Composer, Concept Artist, Sound Designer)")
		addContributor("FirstMegaGame4 (Lead Developer, Project Manager)")
		addContributor("Chatoine (Modeler)")
		addContributor("Contributors [Aerod (Additional Art); Tim Tim Rurkowski (Composer); Rotch Gwylt (Composer); Scarecrowman (Composer)]")
		addContributor("Past [Aethyus (as Former Forge Version Developer trough MCreator); Mystoxi (Help on MCreator); Tenkite (Old Additional Art)]")
		withContact {
			it.homepage = "https://mmodding.com"
			it.sources = "https://github.com/MModding/archeon"
			it.issues = "https://github.com/MModding/archeon/issues"
		}
		environment = EnvironmentTarget.ANY
		withEntrypoints {
			it.init("com.mmodding.archeon.Archeon")
			it.client("com.mmodding.archeon.client.ArcheonClient")
			it.custom("mmodding_bootstrap_init", "com.mmodding.archeon.bootstrap.ArcheonBootstrap")
		}
		addMixin("archeon.mixins.json")
		withDependencies {
			it.javaVersion = ">=" + 17
			it.minecraftVersion = "~" + libs.versions.minecraft.get()
			it.fabricLoaderVersion = ">=" + libs.versions.fabric.loader.get()
			it.fabricApiVersion = ">=" + libs.versions.fabric.api.get()
			it.addDependency("mmodding_lib", ">=" + libs.versions.mmodding.get() + "-")
			// it.mmoddingLibraryVersion = ">=" + libs.versions.mmodding.get()
		}
		withCustom {
			it.put("fluidlogged", "archeon.fluidlogged.json")
		}
	}
}

processResources {
	inputs.property 'version', version

	filesMatching('fabric.mod.json') {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Still required by IDEs such as Eclipse and Visual Studio Code
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25

	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()
}

// If you plan to use a different file for the license, don't forget to change the file name here!
["jar", "sourcesJar"].each {
	tasks.named(it).configure {
		from("LICENSE.md") {
			rename { "${it}_${project.name}"}
		}
	}
}

// Configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
