[versions]
java = "25"
minecraft = "26.1.1"
fabric_loader = "0.18.4"

fabric_api = "0.145.4+26.1.1"
mmodding = "7b541b7f5c"

# Optional Dependencies

trinkets = "4.0.0-alpha.7+26.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
mmodding = { module = "com.mmodding:mmodding-library", version.ref = "mmodding" }

# Optional Dependencies

trinkets = { module = "eu.pb4:trinkets", version.ref = "trinkets" }

[plugins]
fabric_loom = { id = "net.fabricmc.fabric-loom", version = "1.16+" }
mmodding_gradle = { id = "com.mmodding.gradle", version = "0.1.3" }
